name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 6'
jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v6.0.1
      - uses: ./.github/actions/setup
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          cache-level: "strict"
      - uses: ./.github/actions/check-compile
      - uses: ./.github/actions/check-clippy
      - uses: ./.github/actions/check-rustfmt
      - uses: ./.github/actions/check-documentation
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v6.0.1
      - uses: ./.github/actions/setup
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          cache-level: "strict"
      - uses: ./.github/actions/test-compile
      - uses: ./.github/actions/test-client
      - uses: ./.github/actions/test-server
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v6.0.1
      - uses: ./.github/actions/setup
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          cache-level: "strict"
      - uses: ./.github/actions/build-client
      - uses: ./.github/actions/build-server
      - uses: ./.github/actions/build-demo
  publish-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - uses: ./.github/actions/setup
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          cache-level: "off"
      - uses: ./.github/actions/publish-dry-run
