name: Publish Rust crates
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.0
      - uses: ./.github/actions/setup
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          cache-level: "off"
      - uses: ./.github/actions/publish
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
